export const layout = `
  <section id="quay" aria-label="Scène du Quai 17"></section>
  <header class="masthead"><div class="eyebrow">ANGLE MORT / QUAI 17</div><h1 id="situation-title">Apprendre à livrer</h1><p id="objective">Apportez la pièce de R1 à l’atelier.</p></header>
  <nav class="main-tools" aria-label="Jeu et aide"><button id="show-modes">Jouer / changer de mode</button><button id="show-help">Comment jouer ?</button><button id="restart" title="Repartir du début du mode actuel. Les actions de cet essai seront perdues.">Recommencer</button></nav>
  <details class="camera-controls"><summary>Affichage du quai</summary><p>Ces réglages changent votre point de vue. Ils ne font pas avancer le jeu et ne révèlent rien de plus.</p><div class="segmented"><button id="frame-quai" aria-pressed="false">Vue du quai</button><button id="frame-coursive" aria-pressed="true">Vue haute</button></div><div class="view-tools"><button id="zoom-out" aria-label="Dézoomer">−</button><button id="zoom-in" aria-label="Zoomer">+</button><button id="cutaway" aria-pressed="true" title="Masquer le bâtiment permet de suivre les robots déjà observés. Aucun objet inconnu n’apparaît.">Masquer le hangar</button></div></details>
  <aside id="help-panel" aria-label="Objectif et prochaine action">
    <section id="guide"><div id="guide-progress" class="section-kicker"></div><h2 id="guide-title"></h2><p id="guide-body"></p><button id="guide-action"></button></section>
    <section id="challenge-tools" hidden><span id="challenge-clock"></span><button id="show-contract">Vos objectifs</button><button id="show-result" hidden>Bilan final</button><button id="guide-defi" title="Le guide propose les prochaines actions. Cet essai devient un entraînement et ne remplace pas le record.">Guidage pas à pas · entraînement</button></section>
    <aside id="context" class="context-panel" aria-label="Fiche contextuelle" hidden></aside>
    <section id="receipt" class="receipt" role="status" hidden></section>
    <section class="legend" aria-label="Comprendre les observations"><strong>Ce que vous savez</strong><span><i class="live"></i> Plein : vu ce tour</span><span><i class="dated"></i> Hachuré : ancienne observation</span><span><i class="unknown">?</i> Inconnu : aucune confirmation actuelle</span></section>
  </aside>
  <footer class="bottom-bar"><section class="robots" aria-label="Rapports des robots"><div class="section-kicker">CHOISIR UN ROBOT</div><div id="robot-cards" class="robot-cards"></div></section><section id="turn-feedback" role="status" aria-live="polite"><strong id="feedback-title">Le monde est en pause.</strong><span id="feedback-detail">Choisir un robot ou une destination ne consomme aucun tour.</span></section><section class="pulse-controls"><div class="pulse-status"><span id="preparation-status">EN PAUSE</span><span id="pulse">Tour 0</span></div><div class="execution-row"><button id="cancel" hidden>Annuler</button><button id="advance">Exécuter · 1 tour</button></div><p id="execution-hint">Préparez une destination pour commencer.</p></section></footer>
  <dialog id="modes" aria-labelledby="modes-title"><header><h2 id="modes-title">Que voulez-vous jouer ?</h2><button id="close-modes" aria-label="Fermer les modes">×</button></header><p>Changer de mode repart du début. Chaque essai est indépendant.</p><button id="scenario-intro" class="mode-choice"><strong>Apprendre</strong><span>Deux livraisons guidées pour comprendre les robots, les destinations et les tours. Sans score.</span></button><button id="scenario-challenge" class="mode-choice"><strong>S’entraîner · Dernier passage</strong><span>La pompe attend sa batterie. Apprenez à observer une porte inconnue avant de choisir une route. Départ au tour 4, sans record.</span></button><button id="scenario-defi" class="mode-choice"><strong>Défi · Tenir jusqu’au matin</strong><span>16 tours. Maintenez le pompage, laissez passer les ferries et livrez les fournitures. Bilan sur 1 200 points à la fin.</span></button></dialog>
  <dialog id="help" aria-labelledby="help-title"><header><h2 id="help-title">Vous dirigez les livraisons du quai</h2><button id="close-help" aria-label="Fermer l’aide">×</button></header><ol><li><strong>Choisissez un robot.</strong> Sa fiche indique où il a été vu et ce qu’il transporte.</li><li><strong>Choisissez une destination.</strong> Le trajet est proposé avec les informations reçues. Vous pouvez encore annuler.</li><li><strong>Exécutez un tour.</strong> Chaque robot avance au plus d’un tronçon. Le monde évolue, puis se remet en pause. Répétez si la destination est plus loin.</li></ol><h3>Comment savoir si c’est réussi ?</h3><p>Un trajet proposé n’est pas encore une livraison. Attendez la confirmation « Livraison reçue » du destinataire. En défi, il faut aussi respecter le délai indiqué dans Vos objectifs ; les points ne sont révélés qu’à la fin.</p><h3>À quoi servent les lieux ?</h3><p><strong>Dépôt :</strong> récupérer les colis. <strong>Atelier / infirmerie :</strong> remettre les fournitures / colis médicaux. <strong>Pompe :</strong> recevoir une batterie et récupérer les colis du casier. <strong>Transfert :</strong> poser un colis, sans le livrer au destinataire.</p><p><strong>Porte :</strong> contrôle le raccourci. <strong>Passerelle :</strong> les robots passent quand elle est abaissée ; le ferry passe quand elle est levée. <strong>Poste d’observation :</strong> y placer un robot permet de voir la porte.</p><p>Les vues et le hangar masqué servent seulement à mieux lire le quai. Pour obtenir une information nouvelle, déplacez un observateur. Une silhouette hachurée montre la dernière position connue.</p><p><strong>Clavier :</strong> Tab et Entrée pour les boutons ; 1 / 2 pour les robots ; A pour l’atelier ; Échap pour annuler la préparation.</p></dialog>
  <dialog id="challenge-contract" aria-labelledby="contract-title"><header><h2 id="contract-title">Vos objectifs pour cette période</h2><button id="close-contract" aria-label="Fermer les objectifs">×</button></header><p id="contract-period"></p><ul id="challenge-needs"></ul><h3>Ce qui compte</h3><p>Une demande vraiment satisfaite dans le délai vaut 100 points, une seule fois. Déposer au transfert, reclasser la demande ou répéter un reçu ne rapporte rien. Le maximum du poste est 1 200 points ; votre bilan arrive après le dernier tour.</p><p>Pour les trois dernières demandes, chaque service doit encore fonctionner à la fin du tour 16. Une livraison suivie d’un démantèlement ne suffit pas.</p><details><summary>Horaires et règles complètes</summary><p>Quatre périodes : tours 1–4, 5–8, 9–12, 13–16. Chaque période a trois demandes : pompage, ferry, fournitures. Une livraison anticipée ou tardive ne remplace pas une autre demande.</p><p>Passerelle levée pendant les tours 1–2, 5–6, 9–10 et 13–14 ; ferries aux tours 2, 6, 10 et 14. Les colis des deux dernières périodes sont disponibles au casier de la pompe aux tours 9 et 13.</p><p>Batterie reçue au plus tard au tour 8 : stock conservé. Aux tours 9 ou 10 : pompe sauvée, stock perdu. Plus tard : réparation extérieure nécessaire. Les contrôles de la pompe ont lieu aux tours 4, 12 et 16.</p><p>Un service fonctionne si son alimentation, son installation et son accès fonctionnent. Le poste se termine au tour 16, même avec des pertes. Recommencer ne cumule pas les gains.</p></details></dialog>
  <dialog id="challenge-result" aria-labelledby="result-title"><header><h2 id="result-title">Fin du poste</h2><button id="close-result" aria-label="Fermer le bilan">×</button></header><strong id="final-score"></strong><p id="final-summary"></p><ul id="final-explanations"></ul><div class="result-table"><table><thead><tr><th>Service</th><th>1</th><th>2</th><th>3</th><th>4</th><th>À la fin</th></tr></thead><tbody id="final-grid"></tbody></table></div><label for="share-card">Carte de partage · résultat local déclaratif</label><textarea id="share-card" readonly rows="9"></textarea><button id="copy-result">Copier la carte</button><p id="copy-status" role="status"></p></dialog>
  <div id="loading" role="status">Quai 17…</div><div id="error" role="alert" hidden></div>
`;
